### PR TITLE
Added if statement to prevent null data length on data loop

### PR DESCRIPTION
**Pull request by beardedgeek**

### CODE REVIEW

**Comment by alexweissman** [comment]
Thanks!  Did you test the changes?

**Comment by beardedgeek** [comment]
I haven't sorry no, I'm not sure how. Happy to try if you could give me some guidance.

**Comment by alexweissman** [comment]
Well I just meant, run the code and make sure everything seems to still work.  Nothing fancy ;-)

**Comment by r3wt** [comment]
I have elected to manually merge this PR into 0.2.x branch.

**Comment by alexweissman** [comment]
Thanks.

**Comment by alexweissman** [comment]
No longer supporting v0.2.2.  Thanks though!

**Pull request closed without merging**
