### PR TITLE
Replaced and with &&

### PR DESCRIPTION
**Pull request by dwrj87**
Replaced instances of and with &&, according to #29

### CODE REVIEW

**Comment by alexweissman** [comment]
Thanks!  I should let you (and anyone else who is interested in contributing) know that I'm working on a major rewrite of the UF codebase.  So, I wouldn't spend too much time on the current version of the codebase. 

I could, however, really use some help on the rewrite!  If you're interested, hit me up through my website (http://alexanderweissman.com).

**Comment by alexweissman** [comment]
FYI, here is the branch for the rewrite: https://github.com/alexweissman/UserFrosting/tree/slim

**Comment by alexweissman** [comment]
Hi @dwrj87, this patch turned out to have some bugs due to operator precedence: http://php.net/manual/en/language.operators.precedence.php.  Specifically, `&&` has much higher precedence than `and`, so there are a few places where some explicit grouping with parentheses needs to be done.

Would you might fixing that and then resubmitting your pull request?

**Comment by dwrj87** [comment]
@alexweissman I shall take a look at it next week. While I'm at it I shall do the `or`s too

**Comment by alexweissman** [comment]
Thanks!

**Pull request merged**
